// Generated by Selenium IDE
//import org.junit.Test;
//import org.junit.Before;
//import org.junit.After;
//import static org.junit.Assert.*;
//import static org.hamcrest.CoreMatchers.is;
//import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SeleniumExt1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  public void seleniumExt1() {
    System.setProperty("webdriver.chromw.driver", "D:\\FOURTH_YEAR_I_SEM\\Software Testing\\Selenium Required Material\\chromedriver.exe");
    driver = new ChromeDriver();
    driver.get("https://www.amazon.in/");
    driver.manage().window().setSize(new Dimension(770, 824));
    driver.findElement(By.linkText("Best Sellers")).click();
    js.executeScript("window.scrollTo(0,176.8000030517578)");
    driver.findElement(By.cssSelector("#B07MX26G8P .a-dynamic-image")).click();
    js.executeScript("window.scrollTo(0,2471.199951171875)");
    js.executeScript("window.scrollTo(0,4261.60009765625)");
    driver.findElement(By.name("submit.addToCart")).click();
    driver.close();
  }

  public static void main(String[] args) {
    SeleniumExt1Test t1 = new SeleniumExt1Test();
    t1.seleniumExt1();
  }
}
